### ISSUE TITLE
Enhance prettier / linting to be more opinionated

### ISSUE THREAD

**Issue by pegiadise** [PitcherAG/pitcher-code-style#1]
| lib | rule | my suggestion | reason | 
| ------ | ------ | ------ | ------ |
| prettier | [trailingCommas](https://prettier.io/docs/en/options.html#trailing-commas) | `es5` | extensible object properties via duplicating lines that IMHO it's worth the visual noise of a comma (current prettier default) |
| prettier | [arrowParens](https://prettier.io/docs/en/options.html#arrow-function-parentheses) | `always` | again with the means of extensibility it is much easier to add a comma and a new param (current prettier default) |
| eslint | [prefer-template](https://eslint.org/docs/rules/prefer-template) | `error` | let string concatenation RIP |
| eslint | [dot-notation](https://eslint.org/docs/rules/dot-notation) | `error` | much easier to parse cognitively, leaves `['']` notation for dynamic access  |
| eslint | [no-new-wrappers](https://eslint.org/docs/rules/no-new-wrappers) | `error` | read rule link  |
| eslint | [no-new-object](https://eslint.org/docs/rules/no-new-object) | `error` | read rule link  |
| eslint | [consistent-return](https://eslint.org/docs/rules/consistent-return) | `error` | improves predictability and consistency of code  |
| eslint | [no-confusing-arrow](https://eslint.org/docs/rules/no-confusing-arrow) | `error` | improves parsing ternary logic as function output |
| eslint | [prefer-spread](https://eslint.org/docs/rules/prefer-spread) | `error` | read rule link |
| eslint | [no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins) | `error` | read rule link |
| eslint | [no-param-reassign](https://eslint.org/docs/rules/no-param-reassign) | `error` | one step closer to pure functions and FP best practices |
| eslint | [prefer-arrow-callback](https://eslint.org/docs/rules/prefer-arrow-callback) | `error` | read rule link |
| eslint | [default-case](https://eslint.org/docs/rules/default-case) | `error` | add a default case to those `switch`es |
| eslint | [eqeqeq](https://eslint.org/docs/rules/eqeqeq) | `error` | please no type coercion ```[] == false // true``` |
| eslint | [no-lonely-if](https://eslint.org/docs/rules/no-lonely-if) | `error` | read rule link |
| eslint | [radix](https://eslint.org/docs/rules/radix) | `error` | read rule link |
| eslint | [one-var](https://eslint.org/docs/rules/one-var) | `["error", "never"]` | cleaner and declarative |
| eslint | [object-shorthand](https://eslint.org/docs/rules/object-shorthand) | `["error", "always"]` | :heart_eyes:  |

Last but not least, a rule that really helps in parsing code and basically adds an empty line before each return statement and after each variable declaration. Not that important but it is really helpful in some cases:
```js
    "padding-line-between-statements": [
      "error",
      { "blankLine": "always", "prev": "*", "next": "return" },
      { "blankLine": "always", "prev": ["const", "let", "var"], "next": "*" },
      { "blankLine": "any", "prev": ["const", "let", "var"], "next": ["const", "let", "var"] },
      { "blankLine": "always", "prev": "directive", "next": "*" },
      { "blankLine": "any", "prev": "directive", "next": "directive" }
    ],
```

Looking forward to hearing your opinions and extra rules or any counter arguments that you might have.

**Comment by elibolonur** [comment]
Poll here:
https://forms.gle/WQ6i5kVtzLQc1SCc6

**Comment by wojtiku** [comment]
I am in general against `no-prototype-builtins`. I think the reasoning behind it is very sound BUT we don't really use inheritance so it is not a problem in practice and the 2 times a year you need to use `o.hasOwnProperty` on a plain object that came from the REST API it is a hassle with this rule .

`var hasBarProperty = Object.prototype.hasOwnProperty.call(foo, "bar");` is just so much more verbose than `var hasBarProperty = foo.hasOwnProperty("bar");`

**Comment by wojtiku** [comment]
I know prettier has it here but let's also add `'comma-dangle': ['error', 'always-multiline'],`

Let's also add https://www.npmjs.com/package/eslint-plugin-sort-imports-es6-autofix (has a much better fixer than the `sort-imports`.
```
    "sort-imports-es6-autofix/sort-imports-es6": ["error", {
      "ignoreCase": false,
      "ignoreMemberSort": false,
      "memberSyntaxSortOrder": ["all", "single", "multiple", "none"]
    }],
```

I am also in favour of not using kebap-case in vue anywhere except a few svg attributes that need it and `router-view` component. I think everywhere should be `camelCase` for props/slot names and `PascalCase` for components. Why? This is the only way to have consistent names everywhere which makes working with the code easier. Now when using for prop usages for example you need to check both versions - kebap-case and camelCase. Same with the components. I don't think there are arguments for `<kebap-case />` tag names and props other than "it looks nicer because it is HTML-like" and I don't see any benefits of this at all - it just adds cognitive load and maintenance burden. So I propose we do:
```
'vue/attribute-hyphenation': ['error', 'never', {
   ignore: [
    'stroke-dasharray',
    'stroke-width',
  ],
}],
```

**Comment by pegiadise** [comment]
1. Regarding `no-prototype-builtins`. We already have it as an extension from `eslint:recommended` on `warn` level. My suggestion was just to make it stricter (`error`) and as you said the two times per year that you use it the extra 20 characters are ok-ish.
2. 👍  on the `PascalCase` components and `camelCase` props/slot names. `kebab-case` in template elements strongest argument is the runtime evaluation in older browsers (I think) but since we have a build step, it's irrelevant.

**Comment by wojtiku** [comment]
> Regarding no-prototype-builtins. We already have it as an extension from eslint:recommended on warn level. My suggestion was just to make it stricter (error) and as you said the two times per year that you use it the extra 20 characters are ok-ish.

I meant NOT to add it. I think the benefit of using it will be doubtful but writing and reading it is much harder IMO. I speak from experience where we had it on a project. I am not adamant about it or anything, it was just PITA to work with.

**Comment by elibolonur** [comment]
@wojtiku about PascalCase for components; does the proposal apply for naming files as well, or only for component naming? Also, I do agree with PascalCase. Had this issue `check both kebab-case and camelCase` when writing components.

**Comment by wojtiku** [comment]
I think also files. The more consistent, the better. With files imports will be consistent as well because now we do `import 'aComponentName' from '@/components/atlas/component-name/component-name`. I think we should be doing `import 'AComponentName' from '@/components/atlas/AComponentName'`

**Comment by OrestisZinelis** [comment]
Proposal

https://eslint.org/docs/rules/no-throw-literal

@elibolonur  Could you add it to the existing poll?

**Comment by OrestisZinelis** [comment]
> I think also files. The more consistent, the better. With files imports will be consistent as well because now we do `import 'aComponentName' from '@/components/atlas/component-name/component-name`. I think we should be doing `import 'AComponentName' from '@/components/atlas/AComponentName'`

I could not agree more. Vue components and Classes with PascalCase, on file naming too. The same is used by many react devs  too.

**Comment by OrestisZinelis** [comment]
**padding-line-between-statements**

My proposal

Not after consecutive variable declarations.

NOT

```
const one = 1

const two = 2

const three = 3
```
BUT

```
const one = 1
const two = 2
const three = 3
```
I know there is also this option

```
const one = 1, 
           two = 2,
           three = 3
```

but it doesn't apply to the following case

```
const one = 1
let two = 2
const three = 3
```

**Comment by wojtiku** [comment]
I think this is exactly the way it works looking at the docs 💪

**Comment by OrestisZinelis** [comment]
> **padding-line-between-statements**
> 
> My proposal
> 
> Not after consecutive variable declarations.
> 
> NOT
> 
> ```
> const one = 1
> 
> const two = 2
> 
> const three = 3
> ```
> 
> BUT
> 
> ```
> const one = 1
> const two = 2
> const three = 3
> ```
> 
> I know there is also this option
> 
> ```
> const one = 1, 
>            two = 2,
>            three = 3
> ```
> 
> but it doesn't apply to the following case
> 
> ```
> const one = 1
> let two = 2
> const three = 3
> ```

My mistake @pegiadise . Take it as a compliment

**Comment by OrestisZinelis** [comment]
For radix:

Yes, BUT with 'as-needed option'.  (to save some time from extra typing on the 99% of the cases)

`parseInt("071")` instead of `parseInt("071", 10)`
